<?php
$lang = array(
  'page not found' => "<div class=\"alert alert-error\"> <a class=\"close\" data-dismiss=\"alert\">&times;</a>Error: Page not found. </div>" ,
  'Groups' => 'Groups',
  'Group name:' => 'Group name:',
  'create group' => 'Create group',
  'system group cannot be destroyed' => 'System group cannot be destroyed.',
  'group destroyed successfully' => 'Group is destroyed successfully.',
  'membership destroyed successfully' => 'Membership is destroyed successfully.',
  'group created successfully' => 'Group is created successfully.',
  'membership created successfully' => 'Membership is created successfully.',
  'Themes' => 'Themes',
  'theme enabled successfully' => 'Theme is enabled successfully.',
  'theme disabled successfully' => 'Theme is disabled successfully.',
  'Dashboard' => 'Dashboard',
  'General' => 'General',
  'Discussion' => 'Discussion',
  'Documentation' => 'Documentation',
  'Development' => 'Development',
  'Issues' => 'Issues',
  'New Page' => 'New Page',
  'New Link' => 'New Link',
  'Home' => 'Home',
  'Edit Page' => 'Edit Page',
  'link created successfully' => 'Link is created successfully.',
  'preview created successfully' => 'Preview is created successfully.',
  'Contributors' => 'Contributors',
  'Log In' => 'Log In',
  'Change Password' => 'Change Password'
);
